# Generated by Django 2.1.7 on 2019-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videos_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
