# Generated by Django 2.1.7 on 2019-02-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190224_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='time',
            new_name='Date_time',
        ),
    ]
