# Generated by Django 2.1.7 on 2019-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20190224_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Embed_code',
            field=models.CharField(max_length=2000),
        ),
    ]
