# Generated by Django 2.1.7 on 2019-03-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190224_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Date_time',
        ),
    ]
