# Generated by Django 2.1.7 on 2019-03-27 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_remove_video_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
