# Generated by Django 2.1.7 on 2019-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Date_time',
            new_name='timestamp',
        ),
    ]
